[project]
name = "hologen"
version = "0.2.0"
description = "A library to generate digital holograms."
readme = "README.md"
authors = [
    { name = "Gyokhan Kochmarla", email = "hologen@gyokhan.com" }
]
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.5",
    "ruff>=0.14.8",
    "scipy>=1.16.3",
]

[build-system]
requires = ["poetry-core>=2,<3"]
build-backend = "poetry.core.masonry.api"
